image:
  repository: 457491754064.dkr.ecr.us-east-1.amazonaws.com/final-project-ecr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

config:
  POSTGRES_PORT: 5432
  POSTGRES_HOST: demo-app-db.clqai42ow86h.us-east-1.rds.amazonaws.com
  POSTGRES_USER: django_user
  POSTGRES_DB: django_db
  POSTGRES_PASSWORD: pass9764gd
